export { default as HKForm } from './HoKhauForm';
export { default as NKForm } from './NhanKhauForm';
export { default as RequireRemoving } from './RequireRemovingHousehold';
export { default as DeathConfirm } from './DeathComfirm';
export { default as SeparateHousehold } from './SeparateHousehold';
export { default as ChangePopulation } from './ChangePopulation';
export { default as ChangeHousehold } from './ChangeHousehold';
export { default as FixHouseholdNumber } from './FixHousehold';
export { default as ConfirmAchievement } from './ConfirmAchievement';